name: Docker Image Sync to Aliyun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Pull and Push Docker image to Aliyun
        run: |
          docker pull <source-image-name>:<source-tag>
          docker tag <source-image-name>:<source-tag> registry.cn-hangzhou.aliyuncs.com/crpi-gw9chncs50prg6cu.cn-beijing.personal.cr.aliyuncs.com/dockerysb/dockers/dockers/nginx:latest
          docker push registry.cn-hangzhou.aliyuncs.com/crpi-gw9chncs50prg6cu.cn-beijing.personal.cr.aliyuncs.com/dockerysb/dockers/nginx:latest
